language: node_js
compiler: gcc
sudo: false
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libusb-dev
      - g++-4.8
node_js:
  - "4.1"
  - "0.12"
install:
  - export CXX=g++-4.8
  - $CXX --version
  - npm install
