sudo: false
env:
  - NODE_VERSION=4 CC=clang CXX=clang++
  - NODE_VERSION="0.12"
  - NODE_VERSION="0.10"
before_install:
  - nvm install $NODE_VERSION
before_script:
  - npm install
notifications:
  email:
    on_success: "never"
